### ISSUE TITLE
Personal configuration

### ISSUE THREAD

**Issue by jsYangCode** [HKUST-Aerial-Robotics/DenseSurfelMapping#31]
hi, Mr.wang. would you please give me some advice about why The map is so sparse when VO  provided by VINS-FUSION compare with ORB-SLAM. As shown follow:（white:VINS-fusion for VO&&"DenseSurfelMapping-VINS-supported" for mapping.  color:ORB-SLAM for VO&&"DenseSurfelMapping-master" for mapping）looking forward for your reply! Thank u!
![Screenshot from 2020-06-05 10-35-00](https://user-images.githubusercontent.com/34529308/83830661-3e083380-a718-11ea-874a-0bded653bd45.png)

**Comment by WANG-KX** [comment]
Hi, this is an interesting question that I did not notice before.
I guess the reason is that VINS does not provide good visual-consistent odometry estimations due to the inertial term in the optimization. Since the surfel fusion contains many consistency checks, some surfels are filtered out as outliers.
Just my hypothesis.
